server:
  port: 8080
  servlet:
    context-path: /basis
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password:
    url: jdbc:mysql://localhost:3306/basis?serverTimezone=UTC
    username: root
    druid:
      initial-size: 1
      max-active: 20
      min-idle: 1
      stat-view-servlet:
        allow: true
      test-on-borrow: true
  mail:
    host: --- #发送邮件服务器
    username: -----  #发送邮件的邮箱地址
    password:  ----- #客户端授权码，不是邮箱密码，这个在邮箱设置里面自动生成的
    properties.mail.smtp.port: --- #端口号
    from: -----  # 发送邮件的地址，和上面username一致
    #不设置以下属性会报错：Could not connect to SMTP host: smtp.qq.com, port: 465, response: -1
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
